import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footter";

const Sesation = localFont({
  src: "./fonts/Sansation_Regular.ttf",
  variable: "--font-sesation",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        <main className="min-h-80 py-8 gap-8 flex flex-col items-center">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
